GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON ALL TABLES IN SCHEMA public TO DocApprovalUser;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO DocApprovalUser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO DocApprovalUser;