class GlobalConstants:
    INT_FIELD_VALUE = 0
    CHAR_FIELD_VALUE = 1
    TIME_PERIOD_FIELD_VALUE = 2

    MAX_NAME_LENGTH = 500
    MAX_VARCHAR_LENGTH = 4000
    DEFAULT_VARCHAR_LENGTH = 800
    MAX_CODE_VARCHAR_LENGTH = 50